version: '3.7'

services:
  my-app:
    platform: linux/amd64
    build: .
    image: app:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-db:5432/swe304
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tulli2019
    depends_on:
      - my-db

  my-db:
    platform: linux/amd64
    image: postgres:latest
    environment:
      POSTGRES_DB: swe304
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tulli2019
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

networks:
  my-app:
  my-db:
